/*
 * ##################################################################################
 *
 * XFP internal release pipeline
 * should test intensively with following parts
 * - unit test and report
 * - SonarQube report
 * - Polyspace report
 * - compilation for all possible frameworks
 * - doxygen build and deploy on internal release server
 * - Spinx on internal release server
 * - opengrok report
 * - deploy the library into Artifactory
 *
 */

pipeline {

    agent {
        node {
            label 'epe'
        }
    }

    parameters {

    }

    environment {

    }

    triggers {

    }

    options {
        buildDiscarder(
            logRotator(
                numToKeepStr: '2',
                artifactNumToKeepStr: '2'
            )
        )
        disableConcurrentBuilds()
    }

    stages { // one stages combines all action

        stage('Test1') { // runs on slave
            agent {

            }
            steps('S1') { // one action first executor

            }

            steps('S2') { // one action second executor

            }

        }

        stage('Test2') {

        }

        stage('Parallel1') {
            parallel{

                stages{ //first slave
                    agent {}
                    stage('P1'){
                        steps('SP1'){

                        }
                    }
                }

                stages{ // second slave
                    stage('P1'){
                        steps('SP1'){
                            
                        }
                    }
                }

            }

        }

        stage('Test3'){}

    }

    post {
        failure {

        }

    }
}